#!/usr/bin/env bash
# Generates imports.tf for the dns-cloudflare stack by matching every live
# Cloudflare DNS record (by name/type/content) against the Terraform
# resource addresses declared in main.tf, then emitting one `import` block
# per record with its real Cloudflare record ID.
#
# Why this exists: Cloudflare record IDs are opaque, API-assigned hashes —
# unlike the Azure stack (infra/terraform/dns/imports.tf), whose resource
# IDs are deterministic paths that could be constructed by hand from the
# zone/resource-group/record name alone. There is no way to write correct
# Cloudflare import blocks without querying the API first, so this script
# does that query and the address-matching, instead of imports.tf carrying
# guessed or placeholder IDs.
#
# Requires: curl, jq, and CLOUDFLARE_API_TOKEN in the environment (the same
# scoped Zone:DNS:Edit token variables.tf's cloudflare_api_token expects).
#
# Usage:
#   CLOUDFLARE_API_TOKEN=... ./scripts/generate-imports.sh > imports.tf
#
# Run this once before the first `terraform apply` on this stack (apply
# without importing first would try to CREATE all 22 records again and
# fail on duplicates — they already exist live, created via the BIND
# zone-file import documented in
# docs/plans/azure-subscription-migration-plan.md, Subtask 3). Re-run and
# regenerate imports.tf if main.tf's record set ever changes.

set -euo pipefail

: "${CLOUDFLARE_API_TOKEN:?CLOUDFLARE_API_TOKEN must be set}"
ZONE_NAME="${1:-neuralliquid.ai}"

api() {
  curl -sf -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
    -H "Content-Type: application/json" \
    "https://api.cloudflare.com/client/v4${1}"
}

zone_id=$(api "/zones?name=${ZONE_NAME}" | jq -r '.result[0].id')
if [ -z "${zone_id}" ] || [ "${zone_id}" = "null" ]; then
  echo "Could not resolve zone id for ${ZONE_NAME}" >&2
  exit 1
fi

records=$(api "/zones/${zone_id}/dns_records?per_page=100")

# name/type -> terraform resource address. Content is used only to
# disambiguate the for_each keys that share a name+type (the MX pair and
# the three apex TXT records) — matched by substring since Cloudflare
# normalizes some values (e.g. trailing dots) differently from main.tf.
match_address() {
  local name="$1" type="$2" content="$3"
  case "${name}|${type}" in
    "convolens.${ZONE_NAME}|CNAME") echo 'cloudflare_dns_record.product["convolens"]' ;;
    "omnipost.${ZONE_NAME}|CNAME") echo 'cloudflare_dns_record.product["omnipost"]' ;;
    "cognitive-mesh.${ZONE_NAME}|CNAME") echo 'cloudflare_dns_record.product["cognitive_mesh"]' ;;
    "control.cognitive-mesh.${ZONE_NAME}|CNAME") echo 'cloudflare_dns_record.product["cognitive_mesh_control"]' ;;
    "api.cognitivemesh.${ZONE_NAME}|CNAME") echo 'cloudflare_dns_record.product["cognitive_mesh_api"]' ;;
    "hov.${ZONE_NAME}|CNAME") echo 'cloudflare_dns_record.product["hov"]' ;;
    "login.hov.${ZONE_NAME}|CNAME") echo 'cloudflare_dns_record.product["hov_login"]' ;;
    "asuid.convolens.${ZONE_NAME}|TXT") echo 'cloudflare_dns_record.app_service_validation["convolens"]' ;;
    "asuid.omnipost.${ZONE_NAME}|TXT") echo 'cloudflare_dns_record.app_service_validation["omnipost"]' ;;
    "asuid.cognitive-mesh.${ZONE_NAME}|TXT") echo 'cloudflare_dns_record.app_service_validation["cognitive_mesh"]' ;;
    "asuid.control.cognitive-mesh.${ZONE_NAME}|TXT") echo 'cloudflare_dns_record.app_service_validation["cognitive_mesh_control"]' ;;
    "asuid.api.cognitivemesh.${ZONE_NAME}|TXT") echo 'cloudflare_dns_record.app_service_validation["cognitive_mesh_api"]' ;;
    "asuid.hov.${ZONE_NAME}|TXT") echo 'cloudflare_dns_record.app_service_validation["hov"]' ;;
    "asuid.login.hov.${ZONE_NAME}|TXT") echo 'cloudflare_dns_record.app_service_validation["hov_login"]' ;;
    "${ZONE_NAME}|A") echo 'cloudflare_dns_record.apex_a' ;;
    "${ZONE_NAME}|MX")
      case "${content}" in
        mxa.*) echo 'cloudflare_dns_record.apex_mx["mxa"]' ;;
        mxb.*) echo 'cloudflare_dns_record.apex_mx["mxb"]' ;;
        *) echo "" ;;
      esac
      ;;
    "${ZONE_NAME}|TXT")
      case "${content}" in
        _t8jaqjnoysen3xbm27vutpyb5jp6vl7*) echo 'cloudflare_dns_record.apex_txt["swa_domain_verification"]' ;;
        v=spf1*) echo 'cloudflare_dns_record.apex_txt["mailgun_spf"]' ;;
        openai-domain-verification*) echo 'cloudflare_dns_record.apex_txt["openai_verification"]' ;;
        *) echo "" ;;
      esac
      ;;
    "www.${ZONE_NAME}|CNAME") echo 'cloudflare_dns_record.www' ;;
    "email.${ZONE_NAME}|CNAME") echo 'cloudflare_dns_record.email' ;;
    *) echo "" ;;
  esac
}

echo "# Generated by scripts/generate-imports.sh — do not hand-edit."
echo "# Regenerate instead if the live zone or main.tf's record set changes."
echo

matched=0
unmatched=0
while IFS=$'\t' read -r id name type content; do
  addr=$(match_address "${name}" "${type}" "${content}")
  if [ -z "${addr}" ]; then
    echo "# UNMATCHED: id=${id} name=${name} type=${type} content=${content}" >&2
    unmatched=$((unmatched + 1))
    continue
  fi
  matched=$((matched + 1))
  printf 'import {\n  to = %s\n  id = "%s/%s"\n}\n\n' "${addr}" "${zone_id}" "${id}"
done < <(echo "${records}" | jq -r '.result[] | [.id, .name, .type, .content] | @tsv')

echo "Matched ${matched} record(s), ${unmatched} unmatched (see stderr)." >&2
if [ "${matched}" -ne 22 ]; then
  echo "WARNING: expected 22 records, matched ${matched} — review before applying." >&2
fi
