name: Terraform Validate

on:
  pull_request:
    paths:
      - "infra/terraform/**"
      - ".github/workflows/terraform-*.yml"
  push:
    branches:
      - main
    paths:
      - "infra/terraform/**"
      - ".github/workflows/terraform-*.yml"

permissions:
  contents: read

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_wrapper: false

      - name: Check formatting
        run: terraform fmt -check -recursive infra/terraform

      - name: Init bootstrap without backend
        run: terraform -chdir=infra/terraform/bootstrap/tfstate init -backend=false

      - name: Validate bootstrap
        run: terraform -chdir=infra/terraform/bootstrap/tfstate validate

      - name: Init DNS without backend
        run: terraform -chdir=infra/terraform/dns init -backend=false

      - name: Validate DNS
        run: terraform -chdir=infra/terraform/dns validate

      - name: Init web without backend
        run: terraform -chdir=infra/terraform/web init -backend=false

      - name: Validate web
        run: terraform -chdir=infra/terraform/web validate

      - name: Init shared data without backend
        run: terraform -chdir=infra/terraform/shared-data init -backend=false

      - name: Validate shared data
        run: terraform -chdir=infra/terraform/shared-data validate
